name: philips_hue_dart
version: 0.0.1
homepage: https://github.com/cedricmillet/Philips-Hue-Smart-Home
description: A simple package to control Philips Hue devices

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.3.0